apiVersion: v1
entries:
  icinga-stack:
  - apiVersion: v2
    appVersion: 0.3.0
    created: "2023-10-23T14:40:56.74862271+02:00"
    description: Icinga is a monitoring system which checks the availability of your
      network resources, notifies users of outages, and generates performance data
      for reporting.
    digest: 74762dfaf1b90822b5b2518bae952cc45e7aed78a482d663001f301adcac71fe
    maintainers:
    - email: daniel.bodky@netways.de
      name: Daniel Bodky
      url: https://github.com/mocdaniel
    name: icinga-stack
    type: application
    urls:
    - icinga-stack-0.3.0.tgz
    version: 0.3.0
generated: "2023-10-23T14:40:56.74864071+02:00"
